/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 * Function of this part of the app is to display specific text in the TextArea in response to the 
 * users interaction with the app. I slightly scaled down variation of the Services section.
 */
public class FAQ extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public FAQ() {
        initComponents();
        
        textBoxTA.setText("Please click on one of the six most frequently \n"
                + "asked questions above to view the answers");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        q1BT = new javax.swing.JButton();
        q3BT = new javax.swing.JButton();
        q4BT = new javax.swing.JButton();
        q2BT = new javax.swing.JButton();
        q5BT = new javax.swing.JButton();
        q6BT = new javax.swing.JButton();
        homeBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textBoxTA = new javax.swing.JTextArea();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("FAQ's");
        headerLB.setBounds(160, 20, 70, 30);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q1BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q1BT.setText("What services do you provide?");
        buttonGroup1.add(q1BT);
        q1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1BTActionPerformed(evt);
            }
        });
        q1BT.setBounds(30, 70, 340, 23);
        jLayeredPane1.add(q1BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q3BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q3BT.setText("Are there workshops available?");
        buttonGroup1.add(q3BT);
        q3BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3BTActionPerformed(evt);
            }
        });
        q3BT.setBounds(30, 130, 340, 23);
        jLayeredPane1.add(q3BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q4BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q4BT.setText("Do you provide a proof reading service to students?");
        buttonGroup1.add(q4BT);
        q4BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4BTActionPerformed(evt);
            }
        });
        q4BT.setBounds(30, 160, 340, 23);
        jLayeredPane1.add(q4BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q2BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q2BT.setText("Are the services available to all students?");
        buttonGroup1.add(q2BT);
        q2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2BTActionPerformed(evt);
            }
        });
        q2BT.setBounds(30, 100, 340, 23);
        jLayeredPane1.add(q2BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q5BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q5BT.setText("Is there an office that students can call into?");
        buttonGroup1.add(q5BT);
        q5BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5BTActionPerformed(evt);
            }
        });
        q5BT.setBounds(30, 190, 340, 23);
        jLayeredPane1.add(q5BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        q6BT.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        q6BT.setText("How can part time students avail of services?");
        buttonGroup1.add(q6BT);
        q6BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6BTActionPerformed(evt);
            }
        });
        q6BT.setBounds(30, 220, 340, 23);
        jLayeredPane1.add(q6BT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/HomeButtonLbl.fw.png"))); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 440, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/backButton1.jpg"))); // NOI18N
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        backBTN.setBounds(10, 10, 30, 30);
        jLayeredPane1.add(backBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/navigationBar.jpg"))); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 430, 400, 70);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        textBoxTA.setBackground(new java.awt.Color(102, 102, 102));
        textBoxTA.setColumns(20);
        textBoxTA.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        textBoxTA.setForeground(new java.awt.Color(255, 255, 255));
        textBoxTA.setRows(5);
        jScrollPane2.setViewportView(textBoxTA);

        jScrollPane2.setBounds(20, 260, 360, 140);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/App background.jpg"))); // NOI18N
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1BTActionPerformed
        textBoxTA.setText("We over a range of service to students to assist \n"
                + "them with their academic development in NCI. Please see \n"
                + "our Learning Support Services page on the application \n "
                + "You can also call or email us within working ");
    }//GEN-LAST:event_q1BTActionPerformed

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
       MainPage myMainPage = new MainPage();
       myMainPage.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    private void q2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2BTActionPerformed
        textBoxTA.setText("Yes the services are in place to assist all students who  \n"
                + "require them. For some services, an assessment is required.");
    }//GEN-LAST:event_q2BTActionPerformed

    private void q3BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3BTActionPerformed
       textBoxTA.setText("There are a number of workshops in the areas of: study \n"
               + "preporation techniques, academic writing skills etc held"
               + "throughout the year. Please keep an eye on your student \n"
               + "email for updates on up coming workshops throughout \n"
               + "the year.");
    }//GEN-LAST:event_q3BTActionPerformed

    private void q4BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4BTActionPerformed
        textBoxTA.setText("Yes, NCI's learning support team provide a proof reading \n"
                + "service to students. The avail of this service please contact  \n"
                + "Dr Mike Goldrick (See Contacts Page) \n"
                + "Please note that the latest a submission for proof reading  \n"
                + "will be accepted is five days before the submission deadline. \n"
                + "(For help managing your deadlines, please use the submission \n "
                + "timer on found in the 'service' section of the application\n");
    }//GEN-LAST:event_q4BTActionPerformed

    private void q5BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5BTActionPerformed
        textBoxTA.setText("Yes, the Learning support service is located in room 3.11 \n");
    }//GEN-LAST:event_q5BTActionPerformed

    private void q6BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6BTActionPerformed
        textBoxTA.setText("If you are a part time student and have time restraints \n"
                + "simply call or email us to make an appointment for a more \n"
                + "convientient time");
    }//GEN-LAST:event_q6BTActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        LearnSupPage back = new LearnSupPage();
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FAQ().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JButton q1BT;
    private javax.swing.JButton q2BT;
    private javax.swing.JButton q3BT;
    private javax.swing.JButton q4BT;
    private javax.swing.JButton q5BT;
    private javax.swing.JButton q6BT;
    private javax.swing.JTextArea textBoxTA;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}
