/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapplication;

/**
 *
 * @author x12112267
 * The purpose of this page is to provide the suer with information on service provided by NCI Learning Support.
 * The user simply clicks on one of the buttons representing any one of the 5 services listed and the text box populates with information on that
 * service. In some cases, new buttons appear which when clicked will take a user to a web page containing more information etc.
 * PLEASE NOTE: In relation to the Dyslexia screening button. This will generate an addition button which 
 * will allow the user to view a PDF file. This may not work when the file is zipped and sent over for assessment
 * as the file path or directory will be different on another computer. 
 */
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form Services
     */
    public Services() {
        initComponents();
        
        varkLearnStyleBTN.setVisible(false);
        kolbLearnStyleBTN.setVisible(false);
        edysgateBTN.setVisible(false);
        alertBTN.setVisible(false);
        harvardVidLinkBTN.setVisible(false);
        screeningFormBTN.setVisible(false);
        
        textTA.setText("The Learning Support Service is centred around \n"
                + "some core areas such as academic writing, reading, \n"
                + "researching, studying, note-taking, exam revision \n"
                + "and in general, a focus on aiding a student in all \n"
                + "manners of academic advancement.For more information \n"
                + "on the specific features of the service itself, \n"
                + "click on the below links.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        headerLB = new javax.swing.JLabel();
        manualBTN = new javax.swing.JButton();
        mindTrainingBTN = new javax.swing.JButton();
        screeningBTN = new javax.swing.JButton();
        harvardBTN = new javax.swing.JButton();
        virtualBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTA = new javax.swing.JTextArea();
        homeBTN = new javax.swing.JButton();
        kolbLearnStyleBTN = new javax.swing.JButton();
        varkLearnStyleBTN = new javax.swing.JButton();
        edysgateBTN = new javax.swing.JButton();
        alertBTN = new javax.swing.JButton();
        harvardVidLinkBTN = new javax.swing.JButton();
        screeningFormBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        naviBarLB = new javax.swing.JLabel();
        wrapperLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerLB.setForeground(new java.awt.Color(255, 255, 255));
        headerLB.setText("Services");
        headerLB.setBounds(150, 20, 100, 29);
        jLayeredPane1.add(headerLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        manualBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        manualBTN.setText("Learning Development Manual");
        manualBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualBTNActionPerformed(evt);
            }
        });
        manualBTN.setBounds(40, 70, 320, 30);
        jLayeredPane1.add(manualBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mindTrainingBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        mindTrainingBTN.setText("Mind Training");
        mindTrainingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mindTrainingBTNActionPerformed(evt);
            }
        });
        mindTrainingBTN.setBounds(40, 110, 320, 30);
        jLayeredPane1.add(mindTrainingBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        screeningBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        screeningBTN.setText("Dyslexia Screening");
        screeningBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screeningBTNActionPerformed(evt);
            }
        });
        screeningBTN.setBounds(40, 150, 320, 30);
        jLayeredPane1.add(screeningBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        harvardBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        harvardBTN.setText("Harvard Learning Style");
        harvardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvardBTNActionPerformed(evt);
            }
        });
        harvardBTN.setBounds(40, 190, 320, 30);
        jLayeredPane1.add(harvardBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        virtualBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        virtualBTN.setText("Virtual Learning Center");
        virtualBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virtualBTNActionPerformed(evt);
            }
        });
        virtualBTN.setBounds(40, 230, 320, 30);
        jLayeredPane1.add(virtualBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textTA.setBackground(new java.awt.Color(51, 51, 51));
        textTA.setColumns(20);
        textTA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textTA.setForeground(new java.awt.Color(255, 255, 255));
        textTA.setRows(5);
        jScrollPane1.setViewportView(textTA);

        jScrollPane1.setBounds(40, 270, 320, 120);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/HomeButtonLbl.fw.png"))); // NOI18N
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(170, 440, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        kolbLearnStyleBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        kolbLearnStyleBTN.setText("Kolb Learning Style Test");
        kolbLearnStyleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolbLearnStyleBTNActionPerformed(evt);
            }
        });
        kolbLearnStyleBTN.setBounds(200, 400, 190, 23);
        jLayeredPane1.add(kolbLearnStyleBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        varkLearnStyleBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        varkLearnStyleBTN.setText("Vark Learning Style Test");
        varkLearnStyleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varkLearnStyleBTNActionPerformed(evt);
            }
        });
        varkLearnStyleBTN.setBounds(10, 400, 180, 23);
        jLayeredPane1.add(varkLearnStyleBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edysgateBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        edysgateBTN.setText("Edysgate");
        edysgateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edysgateBTNActionPerformed(evt);
            }
        });
        edysgateBTN.setBounds(10, 400, 180, 23);
        jLayeredPane1.add(edysgateBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        alertBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        alertBTN.setText("Alert");
        alertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertBTNActionPerformed(evt);
            }
        });
        alertBTN.setBounds(200, 400, 190, 23);
        jLayeredPane1.add(alertBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        harvardVidLinkBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        harvardVidLinkBTN.setText("Harvard Referencing Style Video Link");
        harvardVidLinkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvardVidLinkBTNActionPerformed(evt);
            }
        });
        harvardVidLinkBTN.setBounds(50, 400, 290, 23);
        jLayeredPane1.add(harvardVidLinkBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        screeningFormBTN.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        screeningFormBTN.setText("View Dyslexia Screening Form");
        screeningFormBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screeningFormBTNActionPerformed(evt);
            }
        });
        screeningFormBTN.setBounds(75, 400, 260, 23);
        jLayeredPane1.add(screeningFormBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/backButton1.jpg"))); // NOI18N
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        backBTN.setBounds(10, 10, 30, 29);
        jLayeredPane1.add(backBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        naviBarLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/navigationBar.jpg"))); // NOI18N
        naviBarLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        naviBarLB.setBounds(0, 430, 400, 70);
        jLayeredPane1.add(naviBarLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wrapperLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapplication/App background.jpg"))); // NOI18N
        wrapperLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        wrapperLB.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(wrapperLB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
        MainPage myMainPage = new MainPage();
        myMainPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBTNActionPerformed

    
    
    private void mindTrainingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mindTrainingBTNActionPerformed
        textTA.setText("Whilst the practice of mind training has been made \n"
                + "popular in recent times through the usage of gaming \n"
                + "culture, the principles behind such daily mental \n"
                + "workouts has a long history, dating back to ancient \n"
                + "Greece and China. This lineage of puzzling, logic \n"
                + "and numeracy can help every learner improve their \n"
                + "working memory and processing speed, which is a \n"
                + "crucial element during not only exam revision, but \n"
                + "exam performance. To begin your own mental workout, \n"
                + "try the below links from home;");
        
        varkLearnStyleBTN.setVisible(false);
        kolbLearnStyleBTN.setVisible(false);
        edysgateBTN.setVisible(true);
        alertBTN.setVisible(true);
        harvardVidLinkBTN.setVisible(false);
        screeningFormBTN.setVisible(false);
    }//GEN-LAST:event_mindTrainingBTNActionPerformed

    private void manualBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualBTNActionPerformed
        textTA.setText("The Learning Development Manual can provide you with \n"
                + "the tools and advice to become a more effective learner \n"
                + "in Higher Education. Covering four units, the manual \n"
                + "aims to help each student become aware of their learning \n"
                + "style and to adopt an individual learning strategy. \n"
                + "You can also take both the Kolb and Vark Learning style \n"
                + "tests by selecting either of the buttons below.");
        
        varkLearnStyleBTN.setVisible(true);
        kolbLearnStyleBTN.setVisible(true);
        edysgateBTN.setVisible(false);
        alertBTN.setVisible(false);
        harvardVidLinkBTN.setVisible(false);
        screeningFormBTN.setVisible(false);
    }//GEN-LAST:event_manualBTNActionPerformed

    private void virtualBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virtualBTNActionPerformed
        textTA.setText("Can't make an appointment? want help studying \n"
                + "from home? Why not contact Mike for a virtual support \n"
                + "session using a virtual classroom? \n"
                + "\n"
                + "Dr Mike Goldrick \n"
                + "Tel: 01 6599245 \n"
                + "Email: michael.goldrick@ncirl.ie");
        
        varkLearnStyleBTN.setVisible(false);
        kolbLearnStyleBTN.setVisible(false);
        edysgateBTN.setVisible(false);
        alertBTN.setVisible(false);
        harvardVidLinkBTN.setVisible(false);
        screeningFormBTN.setVisible(false);
    }//GEN-LAST:event_virtualBTNActionPerformed

    private void screeningBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screeningBTNActionPerformed
        textTA.setText("Dyslexia screening is a new service being operated \n"
                + "free of charge for all students in NCI. The screening \n"
                + "is suggested to students who feel that they may have \n"
                + "difficulty with reading, writing, spelling or \n"
                + "comprehension. \n"
                + "\n"
                + "To avail of the service please complete the following \n"
                + "survey and bring a printed version to the Learning \n"
                + "Support Office (Room 3:11)");
        
        varkLearnStyleBTN.setVisible(false);
        kolbLearnStyleBTN.setVisible(false);
        edysgateBTN.setVisible(false);
        alertBTN.setVisible(false);
        harvardVidLinkBTN.setVisible(false);
        screeningFormBTN.setVisible(true);
    }//GEN-LAST:event_screeningBTNActionPerformed

    private void harvardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvardBTNActionPerformed
        textTA.setText("Please follow this link to watch a video which \n"
                + "demonstrates how to reference in the Harvard Style:");
        
        varkLearnStyleBTN.setVisible(false);
        kolbLearnStyleBTN.setVisible(false);
        edysgateBTN.setVisible(false);
        alertBTN.setVisible(false);
        harvardVidLinkBTN.setVisible(true);
        screeningFormBTN.setVisible(false);
    }//GEN-LAST:event_harvardBTNActionPerformed

    private void varkLearnStyleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varkLearnStyleBTNActionPerformed
        try {
            
            String URL = "http://www.vark-learn.com/english/page.asp?p=questionnaire";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_varkLearnStyleBTNActionPerformed

    private void kolbLearnStyleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolbLearnStyleBTNActionPerformed
        try {
            
            String URL = "http://www.dentaljuce.com/fruit/page.asp?pid=354";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_kolbLearnStyleBTNActionPerformed

    private void edysgateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edysgateBTNActionPerformed
        try {
            
            String URL = "http://www.edysgate.org/site/index_main.php?lang=en&returnTo=";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_edysgateBTNActionPerformed

    private void alertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertBTNActionPerformed
        try {
            
            String URL = "http://www.7128.com/alert/alert_where.html";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_alertBTNActionPerformed

    private void harvardVidLinkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvardVidLinkBTNActionPerformed
        try {
            
            String URL = "http://www.youtube.com/watch?v=s3Jqc7WGrrE";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_harvardVidLinkBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        LearnSupPage back = new LearnSupPage();
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBTNActionPerformed

    /*PLEASE NOTE: In relation to the Dyslexia screening button. This will generate an addition button which 
 * will allow the user to view a PDF file. This may not work when the file is zipped and sent over for assessment
 * as the file path or directory will be different on another computer. 
 * 
 * Please Note: I based the below code on the work of Michael Myers as found on the website www.Stackoverflow.com
 * Full reference to the author: 
 * Open PDF file on fly from Java application
 *  www.stackoverflow.com (2010) Open PDF file on fly from Java application. [online] Available at: 
 * http://stackoverflow.com/questions/2546968/open-pdf-file-on-fly-from-java-application [Accessed: 4 Apr 2013].
 */
    
    private void screeningFormBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screeningFormBTNActionPerformed
        if (Desktop.isDesktopSupported()){
            try{
                File myPDFFile = new File("H:/Semester 2/Object Orientated Programming/Team C OOP Project/Questionaire.pdf");
                Desktop.getDesktop().open(myPDFFile);               
            }catch (IOException ex){
                
            }
        }
    }//GEN-LAST:event_screeningFormBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Services().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton edysgateBTN;
    private javax.swing.JButton harvardBTN;
    private javax.swing.JButton harvardVidLinkBTN;
    private javax.swing.JLabel headerLB;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kolbLearnStyleBTN;
    private javax.swing.JButton manualBTN;
    private javax.swing.JButton mindTrainingBTN;
    private javax.swing.JLabel naviBarLB;
    private javax.swing.JButton screeningBTN;
    private javax.swing.JButton screeningFormBTN;
    private javax.swing.JTextArea textTA;
    private javax.swing.JButton varkLearnStyleBTN;
    private javax.swing.JButton virtualBTN;
    private javax.swing.JLabel wrapperLB;
    // End of variables declaration//GEN-END:variables
}

